GET http://localhost:3001/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY0B4eXouY29tIiwiaWQiOiI2NmE2OWNmY2U4YzRkYmIzMDc4YTUyY2IiLCJpYXQiOjE3MjIzNjc2NzAsImV4cCI6MTcyMjM3MTI3MH0.1qLEZujCVQeE75Edjih5IpGZy9BGgrELpMLU9TfBDG8